title: "Manchester Consultancy"
description: "A strategic business & management consultancy based in Manchester."
url: ""
baseurl: ""
permalink: pretty
theme: minima

logo: "/assets/images/logo.svg"

home:
  limit_services: 8

collections:
  services:
    output: true
    sort_by: weight
  team:
    output: true

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
